curl --location 'http://localhost:3000'
###
curl --location 'http://localhost:3000' \
--header 'Content-Type: application/json' \
--data '{
    "pathfile": "/Users/maxzavaleta/Desktop/udemy/bienesraices/public/uploads",
    "filename": "0.013oi4a0uao1hdsq1ko3.jpg"
}'
###
curl --location 'http://localhost:3000/0.013oi4a0uao1hdsq1ko3.jpg'
